---
version: "3"

services:
  producer:
    build: producer/
    image: manquius/12factor-producer:0.0.1
    ports:
      - "30001:8080"
    environment:
      PRODUCE_CLIENT: "KAFKA/REDIS"
      TWELVEFACTOR_KAFKA_SERVICE_HOST: "kafka"
      TWELVEFACTOR_REDIS_MASTER_SERVICE_HOST: "redis"
  consumer:
    build: consumer/
    image: manquius/12factor-consumer:0.0.1
    ports:
      - "30002:8080"
    environment:
      CONSUME_CLIENT: "kafka"
      TWELVEFACTOR_KAFKA_SERVICE_HOST: "kafka"
      TWELVEFACTOR_REDIS_MASTER_SERVICE_HOST: "redis"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master

