apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "12factor.fullname" . }}-producer
  labels:
    {{- include "12factor.labels" . | nindent 4 }}-producer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "12factor.selectorLabels" . | nindent 6 }}-producer
  template:
    metadata:
      labels:
        {{- include "12factor.selectorLabels" . | nindent 8 }}-producer
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "12factor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "manquius/producer:0.0.1"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
